### ISSUE TITLE
Homematic Binding does not work with RaspberryMatic Firmware > 3.37.8.20181026

### ISSUE THREAD

**Issue by wseifert** [ThomDietrich/openhab-config#2]
I updated my RaspberryMatic to FW 3.41.11.20181126 & 3.41.11.20181222, with both versions no connection from Openhab Homematic binding is possible:

2018-12-29 10:59:01.868 [ERROR] [matic.handler.HomematicBridgeHandler] - Homematic bridge was set to OFFLINE-COMMUNICATION_ERROR due to the following exception: java.net.ConnectException: Verbindungsaufbau abgelehnt
java.io.IOException: java.net.ConnectException: Verbindungsaufbau abgelehnt
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:94) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:98) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:63) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.getDeviceDescription(RpcClient.java:122) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.getGatewayInfo(RpcClient.java:220) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.HomematicGatewayFactory.loadGatewayInfo(HomematicGatewayFactory.java:47) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.HomematicGatewayFactory.createGateway(HomematicGatewayFactory.java:31) ~[?:?]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.lambda$0(HomematicBridgeHandler.java:85) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Verbindungsaufbau abgelehnt
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:80) ~[?:?]
        ... 14 more
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:355) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:352) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector.access$900(ManagedSelector.java:56) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:289) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:181) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:249) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) ~[?:?]
        ... 1 more
2018-12-29 10:59:11.881 [ERROR] [matic.handler.HomematicBridgeHandler] - Homematic bridge was set to OFFLINE-COMMUNICATION_ERROR due to the following exception: java.net.ConnectException: Verbindungsaufbau abgelehnt
java.io.IOException: java.net.ConnectException: Verbindungsaufbau abgelehnt
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:94) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:98) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:63) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.getDeviceDescription(RpcClient.java:122) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.getGatewayInfo(RpcClient.java:220) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.HomematicGatewayFactory.loadGatewayInfo(HomematicGatewayFactory.java:47) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.HomematicGatewayFactory.createGateway(HomematicGatewayFactory.java:31) ~[?:?]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.lambda$0(HomematicBridgeHandler.java:85) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: Verbindungsaufbau abgelehnt
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[?:?]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:676) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:80) ~[?:?]
        ... 14 more
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:355) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:352) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector.access$900(ManagedSelector.java:56) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:289) ~[?:?]
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:181) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:249) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) ~[?:?]
        ... 1 more

Downgrading to Firmware version 3.37.8.20181026 brings back the connection to Homematic.

greetings from Austria
Werner at Seifert dot email

**Comment by jupe76** [comment]
This probably has nothing to do with openhabian.

Please update to openhab 2.4. There was a change in communication, bin-rpc is not longer possible.

See
[https://github.com/jens-maus/RaspberryMatic/issues/481](url)
